### ISSUE TITLE
2 pages do not have comments regarding component not-present

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#43]
The following two pages did not provide a statement showing the component not present in Collector data:

Impounding Embankment
![impounding](https://user-images.githubusercontent.com/16418393/42397815-e7ad472a-8156-11e8-9d7f-6fd8408f223d.png)

Cut Slopes
![cut slopes](https://user-images.githubusercontent.com/16418393/42397820-ebbd54c2-8156-11e8-9a10-7ab005c4a7e7.png)

Others with a "not-present" component have a message similar to below:
![message](https://user-images.githubusercontent.com/16418393/42397825-f02f7d64-8156-11e8-9ed1-28b54de9f843.png)

**Comment by leeensminger** [comment]
@dobrochtaKCI please confirm this is by design.  Based on our previous conversations, I believe it is.

**Comment by dobrochtaKCI** [comment]
@leeensminger This was more due to the fact that these pages are different from the other pages, because these pages have no specific components.  I have the ability to display these messages. It would probably be better to display them for consistency purposes unless you want them to remain the way they are?

**Comment by leeensminger** [comment]
updated to reduce confusion.  looks ok.
