### ISSUE TITLE
SCM centroid generates an error in the map

### ISSUE THREAD

**Issue by leeensminger** [impittman/PTC-Inspection-Field-Tool#44]
When I initially load the "SCM Inspection Map", I get an error that says a layer is not accessible.  When I click the View button, I get this:

![image](https://user-images.githubusercontent.com/4103847/42399221-f9fcc5b6-813a-11e8-8b10-5ca43ac27e98.png)

**Comment by dobrochtaKCI** [comment]
@leeensminger This error occurs only on the windows version of the application an it is due to a corrupt XML file that is produced. The XML file corrupts when a feature has a field with a domain, but none of the features have a value recorded. I populated a feature with false data and republished the SCM layers. The Centroid layer is now visible in collector.

**Comment by leeensminger** [comment]
appears resolved
