### ISSUE TITLE
SCM polygon geometry is editable

### ISSUE THREAD

**Issue by leeensminger** [impittman/PTC-Inspection-Field-Tool#45]
When I click the edit button to update an SCM inventory, the geometry is also editable.

![image](https://user-images.githubusercontent.com/4103847/42399265-2886b6c6-813b-11e8-89ce-4d73ba498be8.png)

**Comment by dobrochtaKCI** [comment]
@leeensminger I updated the permission settings and the layer geometry is no longer editable.

**Comment by dobrochtaKCI** [comment]
@leeensminger  An additional note for this issue is issue: The Feature layer settings in AGO will need to be updated to enforce attribute only editing every time this service is republished. The service settings will only control the ability to edit the feature, while the feature layer settings provide the additional level of control, but they are reset each time the service is republished.

**Comment by leeensminger** [comment]
discussed may be optional going forward.  closing at this time.
